spring.application.name=Spring-Cloud-API-Gateway
server.port=6001

spring.cloud.gateway.server.webflux.routes[0].id=Login-Module
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:5051
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=Game-Module
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:5052
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/game/**

spring.cloud.gateway.server.webflux.routes[2].id=FCM-Module
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:5053
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notifications/**



