spring.application.name=Spring-Cloud-API-Gateway
server.port=5054

spring.cloud.gateway.routes[0].id=Login-Module
spring.cloud.gateway.routes[0].uri=http://localhost:5051
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=Game-Module
spring.cloud.gateway.routes[1].uri=http://localhost:5052
spring.cloud.gateway.routes[1].predicates[0]=Path=/game/**


