spring.application.name=Hello-AWS-Cognito
server.port=1010

# logging info---------------------
logging.file.name=docker_error.log


#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Walp8wg0E