spring.application.name=AgenticAI-Module
server.port=5054
spring.ai.openai.api-key=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