spring.application.name=Proj01-MS-WishMessage
server.port=4568
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}
server.servlet.context-path=/MS-WishMessage
eureka.client.service-url.default-zone=http://localhost:8761/eureka