# setting instance/application/micro-service name
spring.application.name=Billing-Service

# set port for running the application
server.port=4050

# generating random instance id of the running project.
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}

# registering this project as micro service on eureka server.
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# importing configs or application properties from another project that is running on 8888 port
spring.config.import=optional:configserver:

# activating all endpoints so that one of endpoint =>refreshing configs or application properties of another project that is running on 8888 port
management.endpoints.web.exposure.include=*
