spring.application.name=Game-Module
server.port=5052
spring.config.import=optional:configserver:

resilience4j.circuitbreaker.instances.Login-Module.slidingWindowSize=10
resilience4j.circuitbreaker.instances.Login-Module.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.Login-Module.failureRateThreshold=50
resilience4j.circuitbreaker.instances.Login-Module.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.Login-Module.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.Login-Module.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.Login-Module.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.Login-Module.maxAttempts=3
resilience4j.retry.instances.Login-Module.waitDuration=2s
resilience4j.retry.instances.Login-Module.retryExceptions=java.io.IOException
resilience4j.retry.instances.Login-Module.ignoreExceptions=java.lang.IllegalArgumentException


