spring.application.name=Security-Test-Service
server.port=1012
eureka.client.register-with-eureka=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Walp8wg0E
